Import('env', 'arch', 'cereal', 'messaging', 'common', 'gpucommon', 'visionipc')
lenv = env.Clone()

libs = [cereal, messaging, common, 'OpenCL', 'SNPE', 'symphony-cpu', 'capnp', 'zmq', 'kj', 'yuv', gpucommon, visionipc]


common_src = [
  "../modeld/models/commonmodel.cc",
  "../modeld/runners/snpemodel.cc",
  "../modeld/transforms/loadyuv.c",
  "../modeld/transforms/transform.cc",
  "../modeld/thneed/thneed.cc"
]


if arch == "aarch64":
  libs += ['gsl', 'CB', 'gnustl_shared']
  if not TEST_THNEED:
    common_src += ["thneed/thneed.cc"]
  lenv['CFLAGS'].append("-DUSE_THNEED")
  lenv['CXXFLAGS'].append("-DUSE_THNEED")
elif arch == "larch64":
  libs += ['gsl', 'CB', 'pthread', 'dl']
  if not TEST_THNEED:
    common_src += ["thneed/thneed.cc"]
    lenv['CFLAGS'].append("-DUSE_THNEED")
    lenv['CXXFLAGS'].append("-DUSE_THNEED")
else:
  libs += ['pthread']

  # tell runners to use onnx
  lenv['CFLAGS'].append("-DUSE_ONNX_MODEL")
  lenv['CXXFLAGS'].append("-DUSE_ONNX_MODEL")

  if arch == "Darwin":
    # fix OpenCL
    del libs[libs.index('OpenCL')]
    lenv['FRAMEWORKS'] = ['OpenCL']

    # no SNPE on Mac
    del libs[libs.index('SNPE')]
    del libs[libs.index('symphony-cpu')]
    del common_src[common_src.index('runners/snpemodel.cc')]

common = lenv.Object(common_src)

lenv.Program('_trafficd', [
    "trafficd.cc",
  ]+common, LIBS=libs)

